site_name: USTC Mirror Help
site_description: USTC Mirror Help
site_author: LUG @ USTC
site_url: https://mirrors.ustc.edu.cn/help/
use_directory_urls: false
repo_name: ustclug/mirrorhelp
repo_url: https://github.com/ustclug/mirrorhelp
copyright: |
  © 版权所有 2017 - 2024, LUG@USTC.
  <br>
  除额外注明的地方外，本文档按 CC BY-NC-SA 4.0 许可协议发布。

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: light green
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式
  icon:
    logo: fontawesome/brands/linux
    repo: octicons/mark-github-16
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.sections
    - navigation.top

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - markdown.extensions.def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - includes
  - pymdownx.superfences
  - toc:
      permalink: true

extra:
  social:
    - icon: octicons/globe-16
      link: https://lug.ustc.edu.cn/
    - icon: octicons/mark-github-16
      link: https://github.com/ustclug
  analytics:
    provider: google
    property: UA-160637954-1

extra_css:
  - css/extra.css

nav:
  - 发行版镜像:
    - alpine.md
    - anthon.md
    - aosp.md
    - archlinux.md
    - archlinuxcn.md
    - archlinuxarm.md
    - blackarch.md
    - centos.md
    - debian.md
    - debian-security.md
    - debian-cd.md
    - debian-cdimage.md
    - debiancn.md
    - deb-multimedia.md
    - epel.md
    - fedora.md
    - freebsd.md
    - freebsd-pkg.md
    - freebsd-ports.md
    - gentoo.md
    - gentoo-portage.md
    - gentoo.git.md
    - kali.md
    - linuxmint.md
    - mageia.md
    - manjaro.md
    - msys2.md
    - opensuse.md
    - openwrt.md
    - packman.md
    - proxmox.md
    - raspberry-pi-os-images.md
    - raspbian.md
    - raspbian-addons.md
    - rocky.md
    - rpmfusion.md
    - scientificlinux.md
    - termux.md
    - termux-its-pointless.md
    - trisquel.md
    - ubuntu.md
    - ubuntu-ports.md
    - ubuntu-old-releases.md
    - ubuntu-releases.md
    - ubuntu-cdimage.md
    - ubuntu-cloud-images.md
  - 语言镜像:
    - clojars.md
    - ghcup.md
    - hackage.md
    - julia.md
    - node.md
    - nodesource.md
    - npm.md
    - pypi.md
    - rubygems.md
    - crates.io-index.md
    - rust-static.md
    - stackage.md
  - 软件镜像:
    - anaconda.md
    - ceph.md
    - CPAN.md
    - CRAN.md
    - docker-ce.md
    - dockerhub.md
    - eclipse.md
    - elpa.md
    - github-release.md
    - brew.git.md
    - homebrew-bottles.md
    - homebrew-core.git.md
    - homebrew-cask.git.md
    - homebrew-cask-versions.git.md
    - homebrew-services.git.md
    - influxdata.md
    - linux.git.md
    - mariadb.md
    - mozilla.md
    - mysql-repo.md
    - nix-channels.md
    - qtproject.md
    - raspberrypi.md
    - ros.md
    - rosdistro.md
    - sagemath.md
    - winget-source.md
    - xbmc.md
  - 其他:
    - rsync-guide.md
    - todo.md
    - contributor.md
